workspace = { members = [ "browser-core"] }
[package]
name = "my-browser"
version = "0.1.0"
edition = "2021"

[dependencies]
noli = { git= "https://github.com/hikalium/wasabi.git", branch = "for_saba" }
